project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "Introduction to ML"
        contents:
          - altair.qmd
          - eda.qmd
      - section: "Classification"
        href: classification.qmd
        contents:
          - categorical_encoding.qmd
          - categorical_pipeline.qmd
      - section: "Natural Language Processing (NLP)"
        contents:
          - ml_text.qmd
          - bagofwords.qmd
          - tfidf.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center